
window.TRIP_DATA = {
  meta: {
    title: "Ash, Jase & Lexie's Excellent Adventure",
    subtitle: "Hello Kitty inspired Japan travel companion · offline-first · iPhone/iPad friendly",
    tripStart: "2026-07-01T10:25:00+10:00",
    audJpyRate: 112.905,
    audJpyAsOf: "2026-06-09 12:56 Melbourne time",
    people: {
      Jase: { diet: "Vegetarian", interests: ["Guitars", "Japan transport", "Mount Fuji", "practical planning"] },
      Ashleigh: { diet: "Vegetarian", interests: ["Hello Kitty", "Sanrio", "shopping", "cute cafés"] },
      Lexie: { diet: "Not vegetarian", foodMode: "Very plain/simple food only", likes: ["chicken nuggets", "hot chips", "chicken noodles", "plain pasta", "simple pizza", "garlic bread", "ice cream", "pancakes", "desserts"], avoids: ["sauces", "spicy food", "seafood", "mixed dishes", "strong flavours"] }
    }
  },
  mapPlaces: [
    {name:"APA Hotel & Resort Tokyo Bay Shiomi", query:"APA Hotel & Resort Tokyo Bay Shiomi, Tokyo", area:"Tokyo Bay / Shiomi"},
    {name:"Narita Airport Terminal 2", query:"Narita Airport Terminal 2", area:"Narita"},
    {name:"Tokyo Disneyland", query:"Tokyo Disneyland Maihama", area:"Maihama / Urayasu"},
    {name:"Sanrio Puroland", query:"Sanrio Puroland Tama Center", area:"Tama Center"},
    {name:"Asakusa Sumo Club", query:"Asakusa Sumo Club Tokyo", area:"Asakusa"},
    {name:"STAND T Fuji meeting point", query:"Tokyo STAND T Mount Fuji tour meeting point", area:"Tokyo Station / meeting point"},
    {name:"Ochanomizu Guitar Street", query:"Ochanomizu Guitar Street Tokyo", area:"Ochanomizu"},
    {name:"Kiddy Land Harajuku", query:"Kiddy Land Harajuku", area:"Harajuku"},
    {name:"Shibuya Sky", query:"Shibuya Sky Tokyo", area:"Shibuya"},
    {name:"teamLab Planets", query:"teamLab Planets Tokyo", area:"Toyosu"}
  ],
  events: [
    {id:"flight-out", date:"2026-07-01", start:"10:25", end:"19:00", title:"Fly Melbourne to Tokyo Narita", type:"Flight", location:"Melbourne Tullamarine T2 → Tokyo Narita T2", details:"QF79, Economy, Airbus A330. Booking DQ3AT8. Seats 51E, 51F, 51G selected.", appleQuery:"Narita Airport Terminal 2", travel:"Qantas flight. On arrival, use Apple Maps offline area for Narita/Tokyo and hotel transfer instructions.", foodJaseAsh:"Confirm vegetarian meals before travel and bring snack backup.", foodLexie:"Pack plain snacks Lexie will eat on the plane: crackers, chips, noodles if permitted, and familiar treats.", suggestions:["Screenshot boarding passes and seat selection.","At Narita, test ALDI roaming before leaving the terminal.","Add the hotel to Apple Maps favourites."], reminders:["Passports", "Qantas tickets offline", "Travel insurance", "ALDI roaming enabled", "Apple Maps offline areas downloaded"]},
    {id:"transfer-arrival", date:"2026-07-01", start:"20:30", end:"22:00", title:"Private transfer: Narita Airport to hotel", type:"Transfer", location:"Narita Airport T2 → APA Hotel & Resort Tokyo Bay Shiomi", details:"Tokyo Airport Transfers, 5–9 pax. Viator booking 1408239259.", appleQuery:"APA Hotel & Resort Tokyo Bay Shiomi", travel:"Use booked private car. Keep hotel address ready in English and Japanese.", foodJaseAsh:"Simple vegetarian convenience-store backup after arrival.", foodLexie:"Convenience-store chips, bread, ice cream or very plain snacks if restaurants are closed.", suggestions:["Take a photo of the pickup point.","Save driver's message if received.","Do not plan sightseeing tonight."], reminders:["Confirm pickup instructions", "Keep phone charged", "Check hotel address"]},
    {id:"sumo", date:"2026-07-02", start:"18:00", end:"20:00", title:"Sumo Entertainment Show with Chicken Hot Pot & Geisha", type:"Experience", location:"Asakusa Sumo Club", details:"Booking ID BR-1239078135. Dinner show in Asakusa for 3 adults.", appleQuery:"Asakusa Sumo Club Tokyo", travel:"Use Tokyo Metro/JR to Asakusa. Arrive early because Asakusa stations can be rabbit warrens.", foodJaseAsh:"The included chicken hot pot is not vegetarian. Contact operator and request vegetarian meals or eat beforehand.", foodLexie:"Chicken hot pot may not suit Lexie if it has mixed ingredients. Bring/plan simple backup: fries, nuggets/KFC/McDonald's nearby, plain noodles where possible.", suggestions:["Watch salt purification and ring rituals.","Take photos before/after where allowed.","Pair morning with Sensō-ji Temple and Nakamise Street."], reminders:["Contact operator about vegetarian meals", "Check if Lexie will eat anything there", "Save ticket offline", "Arrive 30 min early"]},
    {id:"fuji", date:"2026-07-03", start:"08:00", end:"18:00", title:"Mount Fuji Full Day Sightseeing Tour", type:"Tour", location:"Tokyo STAND T meeting point", details:"Booking BR-1360744633 / BK331264594484919. Departure time 8:00 AM at Tokyo STAND T. Guide info expected around 6 PM the day before; check spam.", appleQuery:"Tokyo STAND T", travel:"Plan the route the night before. Be at STAND T by 7:40 AM. Download the meeting point image and Apple Maps Tokyo area.", foodJaseAsh:"Confirm vegetarian lunch or bring substantial backup. Fuji tours often use set menus with fish/chicken/meat stock.", foodLexie:"Pack Lexie-safe plain food: chips, crackers, plain bread, familiar snacks. Do not rely on tour lunch.", suggestions:["Look for Lake Kawaguchi, Chureito Pagoda/Oshino Hakkai depending on final route.","Bring jacket and comfortable shoes.","Use the journal prompt: first reaction when Fuji appears."], reminders:["Check guide email/spam after 6 PM on 2 July", "Pack power bank", "Pack vegetarian and Lexie food", "Meet 7:40 AM"]},
    {id:"free-july4", date:"2026-07-04", start:"10:00", end:"21:00", title:"Suggested free day: TeamLab + Ginza/Shibuya", type:"Suggested", location:"Toyosu / Ginza / Shibuya", details:"Big open day. Best use: one signature Tokyo experience without overloading the trip.", appleQuery:"teamLab Planets Tokyo", travel:"Use Apple Maps transit when online; keep offline notes for Toyosu, Ginza and Shibuya.", foodJaseAsh:"Pick a vegetarian restaurant ahead: T's TanTan, Ain Soph, Brown Rice, or vegan ramen.", foodLexie:"Build the day around simple backup stops: McDonald's/KFC, fries, plain bakery items, pancakes or ice cream.", suggestions:["Top pick: teamLab Planets.","Add Ginza/Character Street shopping.","Finish with Shibuya Sky if booked, or Tokyo Metropolitan Government Building for a free view."], reminders:["Book timed attractions", "Save routes", "Check food stops for both vegetarian and Lexie-safe options"]},
    {id:"free-july5", date:"2026-07-05", start:"10:00", end:"20:00", title:"Suggested free day: Harajuku + Ochanomizu Guitar Street", type:"Suggested", location:"Harajuku / Shibuya / Ochanomizu", details:"Split-interest day: kawaii shopping and Sanrio for Ash/Lexie, guitar heaven for Jase, then reunite.", appleQuery:"Kiddy Land Harajuku", travel:"Set a reunion point and time before splitting up. Save both areas offline in Apple Maps.", foodJaseAsh:"Harajuku/Shibuya have better vegetarian choices than many areas.", foodLexie:"Harajuku has fries, pancakes, ice cream, crepes and simple café options. Avoid sauce-heavy meals.", suggestions:["Ash/Lexie: Kiddy Land, Takeshita Street, Sanrio stores, purikura.","Jase: Ochanomizu Guitar Street, Ishibashi, Ikebe, TC Gakki.","Meet later at Shibuya Crossing/Hachikō."], reminders:["Power banks", "Shared meeting spot", "Apple Maps favourites saved"]},
    {id:"sanrio", date:"2026-07-06", start:"09:00", end:"17:00", title:"Sanrio Puroland Tokyo", type:"Theme park", location:"Sanrio Puroland, Tama-Center", details:"Hello Kitty Theme Park Admission. 3 adults.", appleQuery:"Sanrio Puroland Tama Center", travel:"Longer train day to Tama-Center. Leave with a buffer and keep phone batteries healthy.", foodJaseAsh:"Desserts/drinks are easier, but savoury meals may use animal stock. Bring backup snacks.", foodLexie:"Likely easier than many days: desserts, ice cream, chips/fries if available, pizza/café items. Check sauces and toppings.", suggestions:["Do not miss Hello Kitty photo areas, My Melody, Kiki & Lala, themed cafés and parades.","Shop early for exclusive items.","Use Lexie's journal stamp: Hello Kitty Adventure."], reminders:["Download tickets", "Check opening hours", "Download Tama offline area", "Pack backup food"]},
    {id:"disney", date:"2026-07-07", start:"09:00", end:"21:00", title:"Tokyo Disneyland", type:"Theme park", location:"Tokyo Disneyland / Maihama", details:"Tokyo Disney Resort reservation A00572968388. Park ticket for July 7, 2026.", appleQuery:"Tokyo Disneyland Maihama", travel:"From Shiomi, JR Keiyo Line toward Maihama is usually straightforward. Leave early for queues.", foodJaseAsh:"Use the Disney app/allergen information and ask staff. Watch hidden meat/fish stock.", foodLexie:"Best likely picks: fries, popcorn, ice cream, bakery items, pizza/plain items and chicken nuggets/tenders if available. Avoid sauces. Pack a safe snack kit.", suggestions:["Morning: enter early, scan tickets, book Priority Pass/standby if available.","Family picks: Beauty and the Beast, Pooh's Hunny Hunt, Monsters Inc, Haunted Mansion, Pirates, Jungle Cruise, Western River Railroad.","Photo spots: Cinderella Castle, World Bazaar, popcorn buckets, night parade/fireworks.","Lexie missions: find Mickey, choose a favourite ride, take a castle photo, pick a snack rating."], reminders:["Install Tokyo Disney Resort App", "Confirm tickets show", "Power banks", "Check parade times", "Pack vegetarian and Lexie snack backup"]},
    {id:"transfer-departure", date:"2026-07-08", start:"15:30", end:"17:30", title:"Private transfer: Tokyo hotel to Narita Airport", type:"Transfer", location:"APA Hotel & Resort Tokyo Bay Shiomi → Narita Airport", details:"Private Transfer to Narita Airport. Viator booking 1408235813.", appleQuery:"Narita Airport Terminal 2", travel:"Use booked private car. Leave margin for traffic.", foodJaseAsh:"Eat before pickup or buy airport vegetarian food early. Carry snacks.", foodLexie:"Buy plain airport snacks or fast food before security if available.", suggestions:["Gentle morning only: pack, local breakfast, last convenience-store shop.","Do not risk a far-away morning activity."], reminders:["Confirm pickup", "Pack chargers", "Check under beds", "Buy plane snacks"]},
    {id:"flight-home", date:"2026-07-08", start:"20:25", end:"07:40", endDate:"2026-07-09", title:"Fly Tokyo Narita to Melbourne", type:"Flight", location:"Tokyo Narita T2 → Melbourne Tullamarine T2", details:"QF80, Economy, Airbus A330. Booking DQ3AT8.", appleQuery:"Melbourne Airport Terminal 2", travel:"Private transfer already booked to Narita.", foodJaseAsh:"Confirm vegetarian return meals and carry backup snacks.", foodLexie:"Carry familiar snacks for Lexie. Airline meals may not be plain enough.", suggestions:["Final souvenirs and water at Narita.","Put passports in the same pocket every time."], reminders:["Arrive early", "Passports", "E-ticket", "Baggage weight", "Food backup"]}
  ],
  lexieMissions: [
    {place:"Disney", icon:"🏰", mission:"Take a castle photo", prompt:"What was your favourite ride or character?", food:"Find a plain snack: fries, popcorn, ice cream or nuggets if available."},
    {place:"Sanrio Puroland", icon:"🎀", mission:"Find Hello Kitty", prompt:"Which Sanrio character made you smile most?", food:"Try a simple dessert or ice cream."},
    {place:"Mount Fuji", icon:"🗻", mission:"Spot Mount Fuji", prompt:"What did Fuji look like when you first saw it?", food:"Use packed plain snacks if lunch looks too mixed."},
    {place:"Asakusa", icon:"⛩️", mission:"Find a lantern or temple gate", prompt:"What was the coolest thing in Asakusa?", food:"Backup: fries/nuggets/plain noodles nearby."},
    {place:"Harajuku", icon:"🌈", mission:"Take a purikura or kawaii shop photo", prompt:"What was the cutest shop?", food:"Look for pancakes, crepes without sauce, ice cream, chips."},
    {place:"Tokyo trains", icon:"🚆", mission:"Ride a train and record the station name", prompt:"Was the train busy or quiet?", food:"Station convenience stores can help with emergency snacks."}
  ],
  translator: {
    phrases: [
      {cat:"Vegetarian", en:"I am vegetarian. No meat or fish, please.", ja:"私はベジタリアンです。肉と魚は入れないでください。", romaji:"Watashi wa bejitarian desu. Niku to sakana wa irenaide kudasai."},
      {cat:"Vegetarian", en:"Does this contain fish stock or meat stock?", ja:"これは魚のだしや肉のだしが入っていますか？", romaji:"Kore wa sakana no dashi ya niku no dashi ga haitte imasu ka?"},
      {cat:"Lexie food", en:"Plain food only, please. No sauce.", ja:"ソースなしで、シンプルな料理だけお願いします。", romaji:"Sōsu nashi de, shinpuru na ryōri dake onegai shimasu."},
      {cat:"Lexie food", en:"Do you have chicken nuggets or chips/fries?", ja:"チキンナゲットかフライドポテトはありますか？", romaji:"Chikin nagetto ka furaido poteto wa arimasu ka?"},
      {cat:"Lexie food", en:"Plain noodles, no sauce please.", ja:"ソースなしのプレーンな麺をお願いします。", romaji:"Sōsu nashi no purēn na men o onegai shimasu."},
      {cat:"Travel", en:"Which platform is this train?", ja:"この電車は何番ホームですか？", romaji:"Kono densha wa nan-ban hōmu desu ka?"},
      {cat:"Travel", en:"Please take us to this hotel.", ja:"このホテルまでお願いします。", romaji:"Kono hoteru made onegai shimasu."},
      {cat:"Emergency", en:"Please call an ambulance.", ja:"救急車を呼んでください。", romaji:"Kyūkyūsha o yonde kudasai."},
      {cat:"Emergency", en:"I need help.", ja:"助けが必要です。", romaji:"Tasukete ga hitsuyō desu."},
      {cat:"Shopping", en:"How much is this?", ja:"これはいくらですか？", romaji:"Kore wa ikura desu ka?"}
    ]
  },
  freeTimeSuggestions: [
    {day:"Arrival evening", best:"Hotel check-in, convenience-store snacks, sleep", why:"Landing at 7 PM plus transfer means recovery time."},
    {day:"2 July morning", best:"Sensō‑ji Temple + Nakamise Street", why:"Pairs perfectly with Asakusa Sumo later."},
    {day:"3 July evening", best:"Easy dinner or Shibuya lights", why:"Fuji tour is a long day; keep optional."},
    {day:"4 July", best:"TeamLab Planets + Ginza/Shibuya", why:"Your biggest open day deserves one big Tokyo wow moment."},
    {day:"5 July", best:"Harajuku/Kiddy Land + Ochanomizu Guitar Street", why:"Matches Ash/Lexie kawaii shopping and Jase guitar interests."},
    {day:"8 July morning", best:"Pack, gentle breakfast, local wander", why:"Private transfer at 3:30 PM means no risky adventure."}
  ],
  checklist: ["Passports valid and packed","Qantas e-ticket saved offline and printed","Vegetarian meals confirmed with Qantas","Tokyo Disney Resort App installed and tickets checked","Viator and Tripadvisor tickets downloaded","Travel insurance policy saved offline","ALDI Mobile roaming enabled for Ashleigh and Jase before leaving Australia","ALDI roaming packs bought/confirmed for Japan","Apple Maps offline areas downloaded: Tokyo, Narita, Disney/Maihama, Tama Center, Fuji/Kawaguchiko","Apple Translate Japanese downloaded for offline use","Medication and prescriptions packed","Power adapters and power banks packed","Hotel address saved in English and Japanese","Suica/PASMO or travel card plan sorted","Vegetarian card screenshot saved","Lexie plain food card screenshot saved","Emergency snacks packed for Jase/Ash and Lexie","Check latest Japan entry and customs requirements before departure","Check Qantas flight status the day before"],
  vegetarianPlaces: ["T's TanTan Tokyo Station: famous vegan ramen and handy for train days.","Ain Soph locations: strong vegan/vegetarian choice.","Brown Rice by Neal's Yard: calm vegetarian-friendly Japanese meal option.","Coco Ichibanya: check vegetarian curry availability and confirm no meat stock.","Convenience store backup: fruit, yoghurt, nuts, bakery sweets, cheese, plain rice snacks after label checking. Beware fish-filled onigiri and dashi."],
  emergency: [{label:"Hotel", value:"APA Hotel & Resort Tokyo Bay Shiomi, 2-8-6 Shiomi, Koto 135-0052 Tokyo"},{label:"Japan emergency police", value:"110"},{label:"Japan ambulance/fire", value:"119"},{label:"Insurance", value:"Qantas/AIG policy 997561692"}]
};
